server:
  port: 8080
spring:
  application:
    name: final_project
  datasource:
    url: jdbc:postgresql://postgres:5432/javadb
    username: postgres
    password: contrasena
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

security:
  jwt:
    secure-access: false
    secret-key: c5cce0a3980ae936bbb7ec9c526f4057043c28b0da0bbb5caca7b713ad2de9df
    access-token-expiration: 3600000
    refresh-token-expiration: 604800000

loggin:
  file:
    path:
      logs/
    name:
      logs/application.log

